[project]
name = "rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "chromadb>=1.3.0",
    "langchain>=1.0.2",
    "pypdf>=6.1.3",
    "pytest>=8.4.2",
]
